spring:
  datasource:
    url: jdbc:mysql://yinianliu.cn:3306/test?useunicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  config:
    activate:
      on-profile: dev