spring:
  datasource:
    url: jdbc:mysql://yinianliu.cn:3306/springboot?useunicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  config:
    activate:
      on-profile: prod

# 全局配置
my-global:
  file-path: /usr/local/fav-upload